### ISSUE TITLE
Consistent treatment of IHO Revision/Document history

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#15]
From @anermina on S5:
> Revision history is placed among annexes in the generated document, while it's placed in the preface in the original. I didn't change this order yet. Please let me know whether IHO documents should include Revision/Document history section in preface. 

We need to confirm how document revision/history is handled inside a document.

_Originally posted by @ronaldtse in https://github.com/metanorma/mn-samples-iho/pull/40#issuecomment-632449138_

**Comment by ronaldtse** [comment]
Asked IHO for clarification:

Some documents contain the document revision history, e.g. S-5/S-8 Guidelines, S-102.

The formats aren’t entirely consistent (as attached). 

The necessary elements seem to be:
- Date
- Edition/Version (also relevant to the other emailed question)
- description of changes
- author (if available)

Can we settle on a consistent format, such as:

——————————————————————————
| Date     |   Version (edition)   |  Authorship   | Description |
——————————————————————————

**Comment by ronaldtse** [comment]
S-5/S-8 Guidelines:
<img width="666" alt="Screen Shot 2020-05-22 at 10 54 53 AM" src="https://user-images.githubusercontent.com/11865/91920961-ee2c0f00-ecfc-11ea-94ac-be1e47ff0bd1.png">


S-102:
<img width="587" alt="Screen Shot 2020-05-22 at 10 53 42 AM" src="https://user-images.githubusercontent.com/11865/91920966-f08e6900-ecfc-11ea-835c-ab73d302ecc7.png">

This is also aligned with NIST and OGC document history.

**Comment by opoudjis** [comment]
Following the work done in the BSI ticket, this is going to be the document history encoding for the samples given:

````
[.preface]
== misc-container

=== document history

- date:
  - type: published
    value:  2017-03
  edition: 2.0.0
  amend:
    - description: Covers both S-5 and S-8
- date:
  - type: published
    value:  2016-07
  edition: 1.1.0
  amend:
    - description: General editing and formatting
    - description: Section 3.2 on time frames modified
      location: clause=3.2
    - description: Modification of section 8.2. Define eligible submission, split review process between individual evaliation and IBSC review process
      location: clause=8.2
    - description: Inserted checklist and flow diagrams to Annex A
      location: annex=A
- date:
  - type: published
    value:  2016-01
  edition: 1.0.0
  amend:
    description: First edition
````

and

````
[.preface]
== misc-container

=== document history

- date:
  - type: published
    value:  2012-04
  edition: 1.0.0
  contributor
  - person:
      name:
        abbreviation: TSMAD
  amend:
    - description: Approved edition of S-102
- date:
  - type: published
    value:  2017-03
  edition: 2.0.0
  contributor
  - organization:
      name: S-102PT
  amend:
    description: >
      Updated clause 4.0 and 12.0.

      Populated clause 9.0 and Annex B.
    location:
      - clause=4.0
      - clause=12.0
      - clause=9.0
      - annex=B
- date:
  - type: updated
    value:  2017-05
  edition: 2.0.0
  contributor
  - organization:
      name: S-102PT
  amend:
    description: >
      Modified clause 9.0 based on feedback at S-100WG2 meeting.
    location:
      - clause=9.0
- date:
  - type: updated
    value:  2018-02
  edition: 2.0.0
  contributor
  - organization:
      name: S-102PT
  amend:
    description: >
      Modified clause 9.0. Deleted contents of Annex B in preparation for updated S-100 Part 10C guidance. Added Annex F: S-102 Dataset Size and Production, Annex G: Gridding Example, Annex H: Statement added for Multi-Resolution Gridding, Annex I: Statement for future S-102 Tiling.
    location:
      - clause=9.0
      - annex=B
      - annex=F
      - annex=G
      - annex=H
      - annex=I
- date:
  - type: updated
    value:  2018-06
  edition: 2.0.0
  contributor
  - organization:
      name: S-102PT
  amend:
    description: >
      Modifications to align with S-100 v4.0.0, S-100 Part 10c development, and actions from 4th April S-102 Project Team Meeting.

      Modified content throughout the following sections:

      * Clause 1, 3, 4, 5, 6, 9, 10, 11, and 12.
      * Annexes A, B, D, F, G, and I.
    location:
      - clause=1
      - clause=3
      - clause=4
      - clause=5
      - clause=6
      - clause=9
      - clause=10
      - clause=11
      - clause=12
      - annex=A
      - annex=B
      - annex=D
      - annex=F
      - annex=G
      - annex=I
````
