### ISSUE TITLE
Change IHO to use Fira Code and Arial (instead of SF Mono and Helvetica Neue)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-iho#39]
IHO doesn't actually use SF Mono or Helvetica Neue, even though this was from their template. 

This task is to use Fira Code and Arial instead.

From @intelligent2013:

> IHO xslt was developed for source doc templates in gh-pages branch (for example, https://raw.githubusercontent.com/metanorma/mn-samples-iho/gh-pages/documents/b12.doc). The main font in docs is "Helvetica Neue":

```css
p.MsoNormal, li.MsoNormal, div.MsoNormal {
  mso-style-unhide: no;
  mso-style-qformat: yes;
  mso-style-parent: "";
  margin: 0cm;
  margin-bottom: 12.0pt;
  mso-pagination: widow-orphan;
  font-size: 12.0pt;
  font-family: "Helvetica Neue",Arial,sans-serif;
  mso-fareast-font-family: "Times New Roman";
  mso-ansi-language: EN-US;
  mso-fareast-language: EN-US; }
```

For source code:
```css
p.Sourcecode, li.Sourcecode, div.Sourcecode, pre.Sourcecode, pre {
  mso-style-unhide: no;
  mso-style-qformat: yes;
  mso-style-parent: "";
  margin-top: 6.0pt;
  margin-right: 0cm;
  margin-bottom: 6.0pt;
  margin-left: 0cm;
  text-align: left;
  mso-pagination: widow-orphan;
  tab-stops: 45.8pt 91.6pt 137.4pt 183.2pt 229.0pt 274.8pt 320.6pt 366.4pt 412.2pt 458.0pt 503.8pt 549.6pt 595.4pt 641.2pt 687.0pt 732.8pt;
  font-size: 10.0pt;
  font-family: SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace;
  mso-fareast-font-family: Calibri;
  mso-bidi-font-family: "Courier New";
  mso-ansi-language: EN-GB; }
```

In case if font didn't install on system, then MS Word uses next first available font. In this case - Arial:
![изображение](https://user-images.githubusercontent.com/5559926/100612985-dfb5b980-3324-11eb-8877-19e031bf8670.png)

_Originally posted by @Intelligent2013 in https://github.com/metanorma/metanorma-standoc/issues/383#issuecomment-735773948_
